version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./sql:/var/lib/mariadb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080